### ISSUE TITLE
Change checkbox and heart color to --accent

### ISSUE THREAD

**Issue by paolozanchi** [paolozanchi/tpts-keyboard#3]

**Comment by eugenekotovx** [comment]
Hi! Can you assignment to me this issue?

**Comment by paolozanchi** [comment]
@eugenekotovx Done! Let me know if you need help!

**Comment by paolozanchi** [comment]
https://stackoverflow.com/questions/32413731/color-for-unicode-emoji

**Comment by paolozanchi** [comment]
Fixed with [4eddaaa5d4397858c754f218c7a5bcec10266550](https://github.com/paolozanchi/tpts-keyboard/commit/4eddaaa5d4397858c754f218c7a5bcec10266550)
